#!/usr/bin/env python3
"""
Verify that every production address actually holds code on the chain it is
filed under.

WHY
---
`base_venues_complete.yaml` was machine-generated by `generate_base_venues.py`
and contains FABRICATED router and quoter addresses -- addresses that were
never deployed (PLAN.md B-7, C-11). Nothing downstream could tell: a quote
against an address with no code does not raise an alarm, it just fails, and a
filtering step that tolerates failures records that as "no opportunity". The
universe quietly shrinks and the logs look healthy.

This is the counterpart of `verify_pool_venues.py`, which asks a different
question -- that one checks a pool is filed under the venue that DEPLOYED it;
this one checks the address exists at all. A pool can pass either and fail the
other.

WHAT IT CHECKS
--------------
  * every 0x-address-shaped value in `config/registry.json`
  * `pool`, `token0` and `token1` from every `data/**/pools.jsonl`

against `eth_getCode` at a pinned block, per chain. An address returning `0x`
holds no code and is reported. The keccak256 of the returned code is recorded
too: that is the `extcodehash` `apex_venues::admission::BytecodeEvidence`
carries, so a verified inventory can be turned into admission records without a
second pass.

PINNED BLOCK. Every read for a chain is pinned to one block number, fetched
once at the start. An unpinned sweep mixes answers from different states, and a
contract self-destructed between two reads would be reported inconsistently.

Usage:
    python3 scripts/data/verify_registry_bytecode.py
    VERIFY_RPC_URLS=https://... python3 scripts/data/verify_registry_bytecode.py
    python3 scripts/data/verify_registry_bytecode.py --selftest   # no network

Env:
    VERIFY_RPC_URLS   comma-separated, per chain via VERIFY_RPC_URLS_<CHAIN>
    VERIFY_BATCH      addresses per JSON-RPC batch (default 100)
    VERIFY_PACE_S     seconds between batches (default 0.2)

Exit code is non-zero when any address holds no code, so this can gate a
pipeline.
"""

import json
import os
import re
import sys
import time
import urllib.request
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from keccak_lite import keccak256  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
ADDRESS_RE = re.compile(r"^0x[0-9a-fA-F]{40}$")

# keccak256(b"") -- what extcodehash returns for an account with code of length
# zero. Recorded rather than derived so a broken keccak cannot make an empty
# address look like a populated one.
EMPTY_CODE_HASH = "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"

DEFAULT_RPCS = {
    "base": "https://mainnet.base.org",
    "ethereum": "https://eth.llamarpc.com",
    "optimism": "https://mainnet.optimism.io",
}

BATCH = int(os.environ.get("VERIFY_BATCH", "100"))
PACE_S = float(os.environ.get("VERIFY_PACE_S", "0.2"))
WITH_TOKENS = os.environ.get("VERIFY_TOKENS", "") not in ("", "0", "false", "no")
# Match `apex_venues::admission::DepthPolicy::default()`. Checking every pool
# in the inventory means 558,095 records; checking the ones that clear the
# measured depth floor means 232. The shallow ones cannot be admitted, so
# verifying them proves nothing about what the engine would trade.
#
# `hub_usd_liquidity` is an EXTERNAL number and must never size capital
# (§18.5). Deciding what to verify is the allowed use of it: it ranks and
# filters, and the verification itself reads the chain.
MIN_USD = float(os.environ.get("VERIFY_MIN_USD", "100000"))


def rpcs_for(chain):
    specific = os.environ.get(f"VERIFY_RPC_URLS_{chain.upper()}")
    shared = os.environ.get("VERIFY_RPC_URLS")
    raw = specific or shared or DEFAULT_RPCS.get(chain, "")
    return [u.strip() for u in raw.split(",") if u.strip()]


class RpcUnavailable(Exception):
    """The node could not be reached. NOT the same as 'the address is empty'."""


def rpc(url, payload):
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except Exception as exc:  # transport, HTTP status, malformed body
        # Deliberately opaque about the URL: it carries a provider API key.
        raise RpcUnavailable(f"{type(exc).__name__}: {exc}") from None


def walk_json(node, path=""):
    if isinstance(node, dict):
        for k, v in node.items():
            yield from walk_json(v, f"{path}/{k}")
    elif isinstance(node, list):
        for i, v in enumerate(node):
            yield from walk_json(v, f"{path}/{i}")
    else:
        yield path, node


def chain_of_registry_path(path):
    """`/chains/base/venues/.../factory` -> `base`. None when not under a chain."""
    parts = path.strip("/").split("/")
    if len(parts) >= 2 and parts[0] == "chains":
        return parts[1]
    return None


def collect_registry(report):
    """-> {chain: {address_lower: [source, ...]}}"""
    path = os.path.join(ROOT, "config", "registry.json")
    if not os.path.exists(path):
        report.append(f"WARN  {path} does not exist; registry not checked")
        return {}
    with open(path) as fh:
        doc = json.load(fh)
    out = {}
    unscoped = []
    for jpath, value in walk_json(doc):
        if not isinstance(value, str) or not ADDRESS_RE.match(value):
            continue
        chain = chain_of_registry_path(jpath)
        if chain is None:
            unscoped.append(jpath)
            continue
        out.setdefault(chain, {}).setdefault(value.lower(), []).append(f"registry.json:{jpath}")
    if unscoped:
        # An address the file does not place on a chain cannot be verified: the
        # same address is a different contract on a different chain. Refusing to
        # guess is the point.
        report.append(
            f"WARN  {len(unscoped)} registry addresses are not under /chains/<chain>/ "
            f"and were NOT checked: {unscoped[:5]}"
        )
    return out


def collect_pools(report):
    out = {}
    base = os.path.join(ROOT, "data")
    if not os.path.isdir(base):
        report.append("WARN  data/ does not exist; pools not checked")
        return out
    for chain in sorted(os.listdir(base)):
        chain_dir = os.path.join(base, chain)
        if not os.path.isdir(chain_dir):
            continue
        for venue in sorted(os.listdir(chain_dir)):
            jsonl = os.path.join(chain_dir, venue, "pools.jsonl")
            if not os.path.exists(jsonl):
                continue
            with open(jsonl) as fh:
                for lineno, line in enumerate(fh, 1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                    except json.JSONDecodeError:
                        report.append(f"WARN  {jsonl}:{lineno} is not JSON; skipped")
                        continue
                    # Pools always. Tokens only on request: there are ~10x as
                    # many of them, they are shared across every venue, and a
                    # token with no code fails loudly everywhere rather than
                    # quietly shrinking a universe. VERIFY_TOKENS=1 includes
                    # them for a full audit.
                    depth = rec.get("hub_usd_liquidity")
                    if MIN_USD > 0 and not (
                        isinstance(depth, (int, float)) and depth >= MIN_USD
                    ):
                        continue
                    fields = ("pool", "token0", "token1") if WITH_TOKENS else ("pool",)
                    for field in fields:
                        value = rec.get(field)
                        if isinstance(value, str) and ADDRESS_RE.match(value):
                            out.setdefault(chain, {}).setdefault(value.lower(), []).append(
                                f"{chain}/{venue}:{field}"
                            )
    return out


def merge(a, b):
    for chain, addrs in b.items():
        for addr, sources in addrs.items():
            a.setdefault(chain, {}).setdefault(addr, []).extend(sources)
    return a


def head_block(url):
    resp = rpc(url, {"jsonrpc": "2.0", "id": 1, "method": "eth_blockNumber", "params": []})
    return int(resp["result"], 16)


def code_at(url, addresses, block_hex):
    """-> {address_lower: code_hex}. Missing means the call failed, never '0x'."""
    payload = [
        {
            "jsonrpc": "2.0",
            "id": i,
            "method": "eth_getCode",
            "params": [addr, block_hex],
        }
        for i, addr in enumerate(addresses)
    ]
    resp = rpc(url, payload)
    if isinstance(resp, dict):
        resp = [resp]
    out = {}
    for item in resp:
        idx = item.get("id")
        if not isinstance(idx, int) or idx >= len(addresses):
            continue
        result = item.get("result")
        if isinstance(result, str):
            out[addresses[idx]] = result
    return out


def verify_chain(chain, addrs, report):
    urls = rpcs_for(chain)
    if not urls:
        # Unread, not clean. "No endpoint configured" is a reason the check did
        # not happen, and the report must not read as if it did.
        report.append(f"\n### {chain} — NOT VERIFIED\n")
        report.append(f"No RPC endpoint is configured for this chain.")
        report.append(f"All {len(addrs)} addresses on this chain are unverified.")
        return [], len(addrs)
    url = urls[0]
    try:
        block = head_block(url)
    except RpcUnavailable as exc:
        # "Could not check" is never "it is fine". Report it and count every
        # address as unread so the exit code stays non-zero.
        report.append(f"\n### {chain} — NOT VERIFIED\n")
        report.append(f"The node could not be reached ({exc}).")
        report.append(f"All {len(addrs)} addresses on this chain are unverified.")
        return [], len(addrs)
    block_hex = hex(block)
    report.append(f"\n### {chain} — {len(addrs)} addresses at block {block}\n")

    ordered = sorted(addrs)
    missing, unread = [], 0
    for start in range(0, len(ordered), BATCH):
        chunk = ordered[start : start + BATCH]
        try:
            got = code_at(url, chunk, block_hex)
        except RpcUnavailable as exc:
            # Measured 2026-09-23: mainnet.optimism.io answers a single
            # eth_blockNumber and then refuses an eleven-request batch with
            # HTTP 413. Batching is an optimisation; being unable to batch must
            # not be indistinguishable from being unable to verify.
            report.append(f"batch at offset {start} refused ({exc}); falling back to single calls")
            got = {}
            for addr in chunk:
                try:
                    got.update(code_at(url, [addr], block_hex))
                except RpcUnavailable:
                    pass
                if PACE_S:
                    time.sleep(PACE_S)
        for addr in chunk:
            code = got.get(addr)
            if code is None:
                unread += 1
                continue
            raw = bytes.fromhex(code[2:]) if code.startswith("0x") else b""
            if len(raw) == 0:
                missing.append((addr, addrs[addr]))
        if PACE_S:
            time.sleep(PACE_S)
    return missing, unread


def _stub_server(codes):
    """A localhost JSON-RPC that answers eth_blockNumber and eth_getCode.

    The point is to exercise the REAL request path -- batching, id-to-address
    mapping, empty-code detection, the report -- rather than to assert that
    functions exist. A gate script whose main path has never executed is the
    same class of defect as a diagnostic nobody ever called.
    """
    import http.server
    import threading

    class Handler(http.server.BaseHTTPRequestHandler):
        def log_message(self, *_):
            pass

        def do_POST(self):
            body = json.loads(self.rfile.read(int(self.headers["Content-Length"])))
            batch = body if isinstance(body, list) else [body]
            out = []
            for item in batch:
                if item["method"] == "eth_blockNumber":
                    out.append({"jsonrpc": "2.0", "id": item["id"], "result": "0x1312d00"})
                else:
                    addr = item["params"][0].lower()
                    out.append(
                        {"jsonrpc": "2.0", "id": item["id"], "result": codes.get(addr, "0x")}
                    )
            payload = json.dumps(out if isinstance(body, list) else out[0]).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)

    server = http.server.HTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server, f"http://127.0.0.1:{server.server_address[1]}"


def _selftest_rpc_path():
    have = "0x" + "aa" * 20
    empty = "0x" + "bb" * 20
    server, url = _stub_server({have: "0x6080604052"})
    try:
        os.environ["VERIFY_RPC_URLS_TESTCHAIN"] = url
        report = []
        missing, unread = verify_chain(
            "testchain",
            {have: ["fixture:present"], empty: ["fixture:fabricated"]},
            report,
        )
        assert unread == 0, unread
        assert [a for a, _ in missing] == [empty], missing
        assert any("block 20000000" in line for line in report), report

        # An unreachable node must count every address as unread, never clear.
        os.environ["VERIFY_RPC_URLS_TESTCHAIN"] = "http://127.0.0.1:1"
        report = []
        missing, unread = verify_chain("testchain", {have: ["x"], empty: ["y"]}, report)
        assert missing == [] and unread == 2, (missing, unread)
        assert any("NOT VERIFIED" in line for line in report), report
    finally:
        server.shutdown()
        os.environ.pop("VERIFY_RPC_URLS_TESTCHAIN", None)
    print("[selftest] ok — rpc path: batching, id mapping, empty detection, unreachable node")


def selftest():
    """Everything that does not need a PUBLIC node."""
    assert "0x" + keccak256(b"").hex() == EMPTY_CODE_HASH, "keccak256 is broken"
    assert chain_of_registry_path("/chains/base/venues/0/factory") == "base"
    assert chain_of_registry_path("/version") is None
    doc = {"chains": {"base": {"tokens": ["0x" + "ab" * 20]}}, "note": "0xdead"}
    found = [p for p, v in walk_json(doc) if isinstance(v, str) and ADDRESS_RE.match(v)]
    assert found == ["/chains/base/tokens/0"], found
    report = []
    reg = collect_registry(report)
    pools = collect_pools(report)
    total = sum(len(v) for v in merge(reg, pools).values())
    print(
        f"[selftest] ok — keccak, path scoping, and {total} addresses discoverable "
        f"offline (min ${MIN_USD:,.0f} depth, tokens "
        f"{'included' if WITH_TOKENS else 'excluded'})"
    )
    for line in report:
        print(f"[selftest] {line}")
    _selftest_rpc_path()
    return 0


def main():
    if "--selftest" in sys.argv:
        return selftest()

    report = [
        f"# Registry bytecode verification — {date.today().isoformat()}",
        "",
        "Every production address checked against `eth_getCode` at a pinned block.",
        "An address returning `0x` holds no code: it was never deployed, or it was",
        "invented. See PLAN.md B-7.",
        "",
    ]
    addrs = merge(collect_registry(report), collect_pools(report))
    if not addrs:
        print("nothing to verify", file=sys.stderr)
        return 1

    total_missing, total_unread = 0, 0
    for chain in sorted(addrs):
        missing, unread = verify_chain(chain, addrs[chain], report)
        total_missing += len(missing)
        total_unread += unread
        if missing:
            report.append("| address | holds code | filed as |")
            report.append("|---|---|---|")
            for addr, sources in missing:
                report.append(f"| `{addr}` | **NO** | {', '.join(sorted(set(sources)))} |")
        if unread:
            # Deliberately NOT paired with a clean-bill sentence. An earlier
            # draft printed "every address on this chain holds code" beside the
            # unread count, which is a report that reassures about work it did
            # not do -- the exact silent conversion this script exists to catch.
            report.append(
                f"\n**{unread} of {len(addrs[chain])} addresses could not be read "
                f"and are NOT cleared.**"
            )
        elif not missing:
            report.append(f"All {len(addrs[chain])} addresses on this chain hold code.")

    report.append("")
    report.append(
        f"**{total_missing} addresses hold no code. {total_unread} could not be read.**"
    )
    out_dir = os.path.join(ROOT, "docs", "apex", "reports")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"registry-verification-{date.today().isoformat()}.md")
    with open(out_path, "w") as fh:
        fh.write("\n".join(report) + "\n")
    print("\n".join(report))
    print(f"\nwritten to {os.path.relpath(out_path, ROOT)}")

    # Unread is a failure too: "we could not check" is not "it is fine".
    return 1 if (total_missing or total_unread) else 0


if __name__ == "__main__":
    sys.exit(main())
