#!/usr/bin/env bash
# Nothing that git tracks may read the fabricated venue list.
#
# `base_venues_complete.yaml` was machine-generated by `generate_base_venues.py`
# and contains router and quoter addresses that were never deployed (PLAN.md
# B-7, C-11). Neither file is tracked, so neither can arrive through a clone --
# but both exist in at least one working tree, and a future builder reaching for
# "the venue list that is already there" would pull invented addresses into the
# admission path. A quote against an address with no code does not raise an
# alarm; it fails, and a filtering step records that as "no opportunity".
#
# Scope is `git ls-files`: CI checks out from git, so an untracked file is not
# something CI can be protected from, and flagging one makes the gate unusable
# in the working tree that still has it.
#
# Prose is allowed, including Python docstrings and Rust doc comments. The
# modules and tests that exist BECAUSE of this hazard have to name it -- a gate
# that cannot tell code from a comment about code punishes writing the
# explanation down.
set -euo pipefail
exec python3 - "$@" <<'PY'
import io, re, subprocess, sys

BANNED = re.compile(r"base_venues_complete|generate_base_venues")
SUFFIXES = (".rs", ".py", ".toml", ".yaml", ".yml", ".json", ".json5", ".sh")
SKIP = ("PLAN.md", "scripts/ci/no_fabricated_venue_sources.sh")

def strip_comments(path, text):
    out = []
    in_doc = None
    for line in text.split("\n"):
        stripped = line
        if path.endswith(".py"):
            # Track triple-quoted blocks so a module docstring is not code.
            i = 0
            while i < len(stripped):
                if in_doc:
                    j = stripped.find(in_doc, i)
                    if j < 0:
                        stripped = stripped[:i]
                        break
                    stripped = stripped[:i] + stripped[j + 3 :]
                    in_doc = None
                    continue
                m = re.search(r'"""|\'\'\'', stripped[i:])
                if not m:
                    break
                start = i + m.start()
                quote = m.group(0)
                k = stripped.find(quote, start + 3)
                if k < 0:
                    in_doc = quote
                    stripped = stripped[:start]
                    break
                stripped = stripped[:start] + stripped[k + 3 :]
                i = start
            stripped = re.sub(r"#.*", "", stripped)
        elif path.endswith(".rs"):
            stripped = re.sub(r"//.*", "", stripped)
        elif path.endswith(".sh"):
            stripped = re.sub(r"#.*", "", stripped)
        elif path.endswith((".toml", ".yaml", ".yml")):
            stripped = re.sub(r"#.*", "", stripped)
        out.append(stripped)
    return out

tracked = subprocess.run(["git", "ls-files"], capture_output=True, text=True, check=True).stdout.split()
offenders = []
for path in tracked:
    if path in SKIP or not path.endswith(SUFFIXES):
        continue
    try:
        text = io.open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        continue
    if not BANNED.search(text):
        continue
    for n, line in enumerate(strip_comments(path, text), 1):
        if BANNED.search(line):
            offenders.append(f"  {path}:{n}: {line.strip()}")

if offenders:
    print("[no_fabricated_venue_sources] the fabricated venue list is referenced in code:", file=sys.stderr)
    print("\n".join(offenders), file=sys.stderr)
    print("[no_fabricated_venue_sources] its addresses were never deployed (PLAN.md B-7).", file=sys.stderr)
    print("[no_fabricated_venue_sources] venue admission requires on-chain bytecode.", file=sys.stderr)
    sys.exit(1)

print("[no_fabricated_venue_sources] ok: no tracked code path reads the fabricated venue list")
PY
