#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CHECK_ONLY=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK_ONLY=1
elif [[ $# -gt 0 ]]; then
  echo "Usage: $0 [--check]" >&2
  exit 64
fi

forge build --extra-output abi

ARTIFACT_PATH="$(find out -type f -name 'MultiVenueArbImplementation.json' | head -n 1 || true)"
if [[ -z "$ARTIFACT_PATH" ]]; then
  echo "Could not find MultiVenueArbImplementation artifact under out/." >&2
  exit 1
fi

TMP_OUTPUT="$(mktemp)"
python3 - "$ARTIFACT_PATH" "$TMP_OUTPUT" <<'PY'
import hashlib
import json
import pathlib
import sys

artifact_path = pathlib.Path(sys.argv[1])
out_path = pathlib.Path(sys.argv[2])
artifact = json.loads(artifact_path.read_text())
abi = artifact.get("abi")
if abi is None:
    raise SystemExit(f"Artifact missing abi: {artifact_path}")

abi_hash = hashlib.sha256(
    json.dumps(abi, separators=(",", ":"), sort_keys=True).encode("utf-8")
).hexdigest()
abi_payload = json.dumps(abi, indent=8)

header = (
    "// This file is auto-generated by scripts/gen_abi_rs.sh\n"
    f"// Source artifact: {artifact_path.as_posix()}\n"
    f"// ABI_SHA256: {abi_hash}\n\n"
)

body = f'''use ethers::contract::abigen;\n\nabigen!(\n    MultiVenueArbExecutor,\n    r#"{abi_payload}"#,\n);\n\npub use multi_venue_arb_executor::{{\n    Loan as ExecutorLoan, PlanLegacy as ExecutorPlanLegacy, PlanV2 as ExecutorPlan,\n    Step as ExecutorStep,\n}};\n'''

out_path.write_text(header + body)
PY

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  if ! cmp -s "$TMP_OUTPUT" src/abi.rs; then
    echo "ABI drift detected: src/abi.rs is out of date. Run bash scripts/gen_abi_rs.sh and commit changes." >&2
    rm -f "$TMP_OUTPUT"
    exit 1
  fi
  echo "ABI is up to date."
  rm -f "$TMP_OUTPUT"
  exit 0
fi

mv "$TMP_OUTPUT" src/abi.rs
echo "Generated src/abi.rs from $ARTIFACT_PATH"
