// This file is auto-generated by scripts/gen_abi_rs.sh
// Source artifact: out/MultiVenueArbImplementation.sol/MultiVenueArbImplementation.json
// ABI_SHA256: 214c5403499151519a4d478d2c3a201ddfa8752ffcd86cbcac46c44e29691e16

use ethers::contract::abigen;

abigen!(
    MultiVenueArbExecutor,
    r#"[
        {
                "type": "constructor",
                "inputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "_executeSteps",
                "inputs": [
                        {
                                "name": "steps",
                                "type": "tuple[]",
                                "internalType": "struct MultiVenueArbImplementation.Step[]",
                                "components": [
                                        {
                                                "name": "op",
                                                "type": "uint8",
                                                "internalType": "enum MultiVenueArbImplementation.Op"
                                        },
                                        {
                                                "name": "data",
                                                "type": "bytes",
                                                "internalType": "bytes"
                                        }
                                ]
                        },
                        {
                                "name": "deadline",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "self",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "vaultAddr",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "aavePool",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "contract IAaveV3Pool"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "canonicalProfitToken",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "circuitCooldown",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "uint256",
                                "internalType": "uint256"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "clearCanonicalProfitToken",
                "inputs": [],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "configAdmins",
                "inputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [
                        {
                                "name": "",
                                "type": "bool",
                                "internalType": "bool"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "executeOperation",
                "inputs": [
                        {
                                "name": "asset",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "amount",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "premium",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "initiator",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "params",
                                "type": "bytes",
                                "internalType": "bytes"
                        }
                ],
                "outputs": [
                        {
                                "name": "",
                                "type": "bool",
                                "internalType": "bool"
                        }
                ],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "executors",
                "inputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [
                        {
                                "name": "",
                                "type": "bool",
                                "internalType": "bool"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "feeRecipient",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "getConfig",
                "inputs": [],
                "outputs": [
                        {
                                "name": "feeBps",
                                "type": "uint16",
                                "internalType": "uint16"
                        },
                        {
                                "name": "maxSlippageBps",
                                "type": "uint16",
                                "internalType": "uint16"
                        },
                        {
                                "name": "deadlineBuffer",
                                "type": "uint32",
                                "internalType": "uint32"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "initialise",
                "inputs": [
                        {
                                "name": "_owner",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "_vault",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "_uni",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "_aavePool",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "_permit2",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "feeBps",
                                "type": "uint16",
                                "internalType": "uint16"
                        },
                        {
                                "name": "maxSlippageBps",
                                "type": "uint16",
                                "internalType": "uint16"
                        },
                        {
                                "name": "deadlineBuffer",
                                "type": "uint32",
                                "internalType": "uint32"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "isCircuitOpen",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "bool",
                                "internalType": "bool"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "lastCircuitTrip",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "uint256",
                                "internalType": "uint256"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "moduleExecBridge",
                "inputs": [
                        {
                                "name": "data",
                                "type": "bytes",
                                "internalType": "bytes"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "moduleExecGeneric",
                "inputs": [
                        {
                                "name": "data",
                                "type": "bytes",
                                "internalType": "bytes"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "moduleExecJit",
                "inputs": [
                        {
                                "name": "op",
                                "type": "uint8",
                                "internalType": "uint8"
                        },
                        {
                                "name": "data",
                                "type": "bytes",
                                "internalType": "bytes"
                        },
                        {
                                "name": "deadline",
                                "type": "uint256",
                                "internalType": "uint256"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "moduleExecSwap",
                "inputs": [
                        {
                                "name": "op",
                                "type": "uint8",
                                "internalType": "uint8"
                        },
                        {
                                "name": "data",
                                "type": "bytes",
                                "internalType": "bytes"
                        },
                        {
                                "name": "deadline",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "recipient",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "vaultAddr",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "onFlashLoan",
                "inputs": [
                        {
                                "name": "initiator",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "token",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "amount",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "fee",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "data",
                                "type": "bytes",
                                "internalType": "bytes"
                        }
                ],
                "outputs": [
                        {
                                "name": "",
                                "type": "bytes32",
                                "internalType": "bytes32"
                        }
                ],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "owner",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "permit2",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "contract IPermit2"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "profitRecipient",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "receiveFlashLoan",
                "inputs": [
                        {
                                "name": "tokens",
                                "type": "address[]",
                                "internalType": "address[]"
                        },
                        {
                                "name": "amounts",
                                "type": "uint256[]",
                                "internalType": "uint256[]"
                        },
                        {
                                "name": "fees",
                                "type": "uint256[]",
                                "internalType": "uint256[]"
                        },
                        {
                                "name": "userData",
                                "type": "bytes",
                                "internalType": "bytes"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "resetCircuit",
                "inputs": [],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "setCanonicalProfitToken",
                "inputs": [
                        {
                                "name": "token",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "setCircuitCooldown",
                "inputs": [
                        {
                                "name": "_cooldown",
                                "type": "uint256",
                                "internalType": "uint256"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "setConfigAdmin",
                "inputs": [
                        {
                                "name": "account",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "allowed",
                                "type": "bool",
                                "internalType": "bool"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "setExecutor",
                "inputs": [
                        {
                                "name": "account",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "allowed",
                                "type": "bool",
                                "internalType": "bool"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "setFeeRecipient",
                "inputs": [
                        {
                                "name": "recipient",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "setProfitRecipient",
                "inputs": [
                        {
                                "name": "recipient",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "setTokenApprovals",
                "inputs": [
                        {
                                "name": "approvals",
                                "type": "tuple[]",
                                "internalType": "struct MultiVenueArbImplementation.TokenApproval[]",
                                "components": [
                                        {
                                                "name": "token",
                                                "type": "address",
                                                "internalType": "address"
                                        },
                                        {
                                                "name": "spender",
                                                "type": "address",
                                                "internalType": "address"
                                        },
                                        {
                                                "name": "amount",
                                                "type": "uint256",
                                                "internalType": "uint256"
                                        }
                                ]
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "setUniswapV2FlashFeeBps",
                "inputs": [
                        {
                                "name": "pair",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "feeBps",
                                "type": "uint16",
                                "internalType": "uint16"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "start",
                "inputs": [
                        {
                                "name": "p",
                                "type": "tuple",
                                "internalType": "struct MultiVenueArbImplementation.PlanLegacy",
                                "components": [
                                        {
                                                "name": "loanToken",
                                                "type": "address",
                                                "internalType": "address"
                                        },
                                        {
                                                "name": "amountIn",
                                                "type": "uint256",
                                                "internalType": "uint256"
                                        },
                                        {
                                                "name": "loanProvider",
                                                "type": "uint8",
                                                "internalType": "enum MultiVenueArbImplementation.LoanProvider"
                                        },
                                        {
                                                "name": "cycleSlippageBps",
                                                "type": "uint16",
                                                "internalType": "uint16"
                                        },
                                        {
                                                "name": "steps",
                                                "type": "tuple[]",
                                                "internalType": "struct MultiVenueArbImplementation.Step[]",
                                                "components": [
                                                        {
                                                                "name": "op",
                                                                "type": "uint8",
                                                                "internalType": "enum MultiVenueArbImplementation.Op"
                                                        },
                                                        {
                                                                "name": "data",
                                                                "type": "bytes",
                                                                "internalType": "bytes"
                                                        }
                                                ]
                                        },
                                        {
                                                "name": "minProfit",
                                                "type": "uint256",
                                                "internalType": "uint256"
                                        }
                                ]
                        }
                ],
                "outputs": [
                        {
                                "name": "grossProfit",
                                "type": "uint256",
                                "internalType": "uint256"
                        }
                ],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "startLegacy",
                "inputs": [
                        {
                                "name": "p",
                                "type": "tuple",
                                "internalType": "struct MultiVenueArbImplementation.PlanLegacy",
                                "components": [
                                        {
                                                "name": "loanToken",
                                                "type": "address",
                                                "internalType": "address"
                                        },
                                        {
                                                "name": "amountIn",
                                                "type": "uint256",
                                                "internalType": "uint256"
                                        },
                                        {
                                                "name": "loanProvider",
                                                "type": "uint8",
                                                "internalType": "enum MultiVenueArbImplementation.LoanProvider"
                                        },
                                        {
                                                "name": "cycleSlippageBps",
                                                "type": "uint16",
                                                "internalType": "uint16"
                                        },
                                        {
                                                "name": "steps",
                                                "type": "tuple[]",
                                                "internalType": "struct MultiVenueArbImplementation.Step[]",
                                                "components": [
                                                        {
                                                                "name": "op",
                                                                "type": "uint8",
                                                                "internalType": "enum MultiVenueArbImplementation.Op"
                                                        },
                                                        {
                                                                "name": "data",
                                                                "type": "bytes",
                                                                "internalType": "bytes"
                                                        }
                                                ]
                                        },
                                        {
                                                "name": "minProfit",
                                                "type": "uint256",
                                                "internalType": "uint256"
                                        }
                                ]
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "startV2",
                "inputs": [
                        {
                                "name": "p",
                                "type": "tuple",
                                "internalType": "struct MultiVenueArbImplementation.PlanV2",
                                "components": [
                                        {
                                                "name": "loans",
                                                "type": "tuple[]",
                                                "internalType": "struct MultiVenueArbImplementation.Loan[]",
                                                "components": [
                                                        {
                                                                "name": "token",
                                                                "type": "address",
                                                                "internalType": "address"
                                                        },
                                                        {
                                                                "name": "amount",
                                                                "type": "uint256",
                                                                "internalType": "uint256"
                                                        },
                                                        {
                                                                "name": "provider",
                                                                "type": "uint8",
                                                                "internalType": "enum MultiVenueArbImplementation.LoanProvider"
                                                        },
                                                        {
                                                                "name": "providerAddr",
                                                                "type": "address",
                                                                "internalType": "address"
                                                        }
                                                ]
                                        },
                                        {
                                                "name": "cycleSlippageBps",
                                                "type": "uint16",
                                                "internalType": "uint16"
                                        },
                                        {
                                                "name": "steps",
                                                "type": "tuple[]",
                                                "internalType": "struct MultiVenueArbImplementation.Step[]",
                                                "components": [
                                                        {
                                                                "name": "op",
                                                                "type": "uint8",
                                                                "internalType": "enum MultiVenueArbImplementation.Op"
                                                        },
                                                        {
                                                                "name": "data",
                                                                "type": "bytes",
                                                                "internalType": "bytes"
                                                        }
                                                ]
                                        },
                                        {
                                                "name": "minProfit",
                                                "type": "uint256",
                                                "internalType": "uint256"
                                        }
                                ]
                        }
                ],
                "outputs": [
                        {
                                "name": "grossProfit",
                                "type": "uint256",
                                "internalType": "uint256"
                        }
                ],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "sweep",
                "inputs": [
                        {
                                "name": "token",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "to",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "amount",
                                "type": "uint256",
                                "internalType": "uint256"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "transferOwnership",
                "inputs": [
                        {
                                "name": "newOwner",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "tripCircuit",
                "inputs": [],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "uniV3",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "contract ISwapRouter02"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "uniswapV2Call",
                "inputs": [
                        {
                                "name": "sender",
                                "type": "address",
                                "internalType": "address"
                        },
                        {
                                "name": "amount0",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "amount1",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "data",
                                "type": "bytes",
                                "internalType": "bytes"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "uniswapV2FlashFeeBps",
                "inputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "address"
                        }
                ],
                "outputs": [
                        {
                                "name": "",
                                "type": "uint16",
                                "internalType": "uint16"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "function",
                "name": "uniswapV3FlashCallback",
                "inputs": [
                        {
                                "name": "fee0",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "fee1",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "data",
                                "type": "bytes",
                                "internalType": "bytes"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "uniswapV3MintCallback",
                "inputs": [
                        {
                                "name": "amount0",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "amount1",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "data",
                                "type": "bytes",
                                "internalType": "bytes"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "updateConfig",
                "inputs": [
                        {
                                "name": "feeBps",
                                "type": "uint16",
                                "internalType": "uint16"
                        },
                        {
                                "name": "maxSlippageBps",
                                "type": "uint16",
                                "internalType": "uint16"
                        },
                        {
                                "name": "deadlineBuffer",
                                "type": "uint32",
                                "internalType": "uint32"
                        }
                ],
                "outputs": [],
                "stateMutability": "nonpayable"
        },
        {
                "type": "function",
                "name": "vault",
                "inputs": [],
                "outputs": [
                        {
                                "name": "",
                                "type": "address",
                                "internalType": "contract IBalancerVault"
                        }
                ],
                "stateMutability": "view"
        },
        {
                "type": "event",
                "name": "BridgeExecuted",
                "inputs": [
                        {
                                "name": "bridge",
                                "type": "address",
                                "indexed": true,
                                "internalType": "address"
                        },
                        {
                                "name": "transferId",
                                "type": "bytes32",
                                "indexed": true,
                                "internalType": "bytes32"
                        },
                        {
                                "name": "feePaid",
                                "type": "uint256",
                                "indexed": false,
                                "internalType": "uint256"
                        },
                        {
                                "name": "elapsed",
                                "type": "uint256",
                                "indexed": false,
                                "internalType": "uint256"
                        },
                        {
                                "name": "targetChainId",
                                "type": "uint256",
                                "indexed": false,
                                "internalType": "uint256"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "CanonicalProfitTokenUpdated",
                "inputs": [
                        {
                                "name": "token",
                                "type": "address",
                                "indexed": true,
                                "internalType": "address"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "CircuitReset",
                "inputs": [
                        {
                                "name": "timestamp",
                                "type": "uint256",
                                "indexed": false,
                                "internalType": "uint256"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "CircuitTripped",
                "inputs": [
                        {
                                "name": "timestamp",
                                "type": "uint256",
                                "indexed": false,
                                "internalType": "uint256"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "ConfigAdminUpdated",
                "inputs": [
                        {
                                "name": "account",
                                "type": "address",
                                "indexed": true,
                                "internalType": "address"
                        },
                        {
                                "name": "allowed",
                                "type": "bool",
                                "indexed": false,
                                "internalType": "bool"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "ConfigUpdated",
                "inputs": [
                        {
                                "name": "feeBps",
                                "type": "uint16",
                                "indexed": false,
                                "internalType": "uint16"
                        },
                        {
                                "name": "maxSlippageBps",
                                "type": "uint16",
                                "indexed": false,
                                "internalType": "uint16"
                        },
                        {
                                "name": "deadlineBuffer",
                                "type": "uint32",
                                "indexed": false,
                                "internalType": "uint32"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "ExecutorUpdated",
                "inputs": [
                        {
                                "name": "account",
                                "type": "address",
                                "indexed": true,
                                "internalType": "address"
                        },
                        {
                                "name": "allowed",
                                "type": "bool",
                                "indexed": false,
                                "internalType": "bool"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "ProfitRealised",
                "inputs": [
                        {
                                "name": "token",
                                "type": "address",
                                "indexed": true,
                                "internalType": "address"
                        },
                        {
                                "name": "grossProfit",
                                "type": "uint256",
                                "indexed": false,
                                "internalType": "uint256"
                        },
                        {
                                "name": "ownerFee",
                                "type": "uint256",
                                "indexed": false,
                                "internalType": "uint256"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "TokenApprovalSet",
                "inputs": [
                        {
                                "name": "token",
                                "type": "address",
                                "indexed": true,
                                "internalType": "address"
                        },
                        {
                                "name": "spender",
                                "type": "address",
                                "indexed": true,
                                "internalType": "address"
                        },
                        {
                                "name": "amount",
                                "type": "uint256",
                                "indexed": false,
                                "internalType": "uint256"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "event",
                "name": "UniswapV2FlashFeeBpsUpdated",
                "inputs": [
                        {
                                "name": "pair",
                                "type": "address",
                                "indexed": true,
                                "internalType": "address"
                        },
                        {
                                "name": "feeBps",
                                "type": "uint16",
                                "indexed": false,
                                "internalType": "uint16"
                        }
                ],
                "anonymous": false
        },
        {
                "type": "error",
                "name": "AlreadyInitialised",
                "inputs": []
        },
        {
                "type": "error",
                "name": "BridgeFailed",
                "inputs": []
        },
        {
                "type": "error",
                "name": "BridgeTimeout",
                "inputs": [
                        {
                                "name": "elapsed",
                                "type": "uint256",
                                "internalType": "uint256"
                        },
                        {
                                "name": "maxDuration",
                                "type": "uint256",
                                "internalType": "uint256"
                        }
                ]
        },
        {
                "type": "error",
                "name": "CircuitOpen",
                "inputs": []
        },
        {
                "type": "error",
                "name": "EmptyRevertData",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidAavePool",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidBridge",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidCanonicalProfitToken",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidDeadline",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidFeeBps",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidGenericAction",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidLoanCount",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidMaxSlippage",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidOwner",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidPermit2",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidProviderAddress",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidRoleAccount",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidRouter",
                "inputs": []
        },
        {
                "type": "error",
                "name": "InvalidVault",
                "inputs": []
        },
        {
                "type": "error",
                "name": "NotConfigAdmin",
                "inputs": []
        },
        {
                "type": "error",
                "name": "NotExecutor",
                "inputs": []
        },
        {
                "type": "error",
                "name": "NotOwner",
                "inputs": []
        },
        {
                "type": "error",
                "name": "Permit2AmountOverflow",
                "inputs": []
        },
        {
                "type": "error",
                "name": "UnsupportedPlanVersion",
                "inputs": []
        }
]"#,
);

pub use multi_venue_arb_executor::{
    Loan as ExecutorLoan, PlanLegacy as ExecutorPlanLegacy, PlanV2 as ExecutorPlan,
    Step as ExecutorStep,
};
