// This file is auto-generated by scripts/gen_abi_rs.sh
// Source artifact: out/executor/MultiVenueArbImplementation.sol/MultiVenueArbImplementation.json
// ABI_SHA256: 5976d9657745d3268f15d0efbfbaad0f37092d57c7fa94a818334465e87dfd33

use ethers::contract::abigen;

abigen!(
    MultiVenueArbExecutor,
    r#"[
        {
                "inputs": [
                        {
                                "components": [
                                        {
                                                "components": [
                                                        {
                                                                "internalType": "address",
                                                                "name": "token",
                                                                "type": "address"
                                                        },
                                                        {
                                                                "internalType": "uint256",
                                                                "name": "amount",
                                                                "type": "uint256"
                                                        },
                                                        {
                                                                "internalType": "uint8",
                                                                "name": "provider",
                                                                "type": "uint8"
                                                        },
                                                        {
                                                                "internalType": "address",
                                                                "name": "providerAddr",
                                                                "type": "address"
                                                        }
                                                ],
                                                "internalType": "struct MultiVenueArbImplementation.Loan[]",
                                                "name": "loans",
                                                "type": "tuple[]"
                                        },
                                        {
                                                "internalType": "uint16",
                                                "name": "cycleSlippageBps",
                                                "type": "uint16"
                                        },
                                        {
                                                "components": [
                                                        {
                                                                "internalType": "uint8",
                                                                "name": "op",
                                                                "type": "uint8"
                                                        },
                                                        {
                                                                "internalType": "bytes",
                                                                "name": "data",
                                                                "type": "bytes"
                                                        }
                                                ],
                                                "internalType": "struct MultiVenueArbImplementation.Step[]",
                                                "name": "steps",
                                                "type": "tuple[]"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "minProfit",
                                                "type": "uint256"
                                        }
                                ],
                                "internalType": "struct MultiVenueArbImplementation.PlanV2",
                                "name": "plan",
                                "type": "tuple"
                        }
                ],
                "name": "startV2",
                "outputs": [
                        {
                                "internalType": "uint256",
                                "name": "grossProfit",
                                "type": "uint256"
                        }
                ],
                "stateMutability": "nonpayable",
                "type": "function"
        },
        {
                "inputs": [
                        {
                                "components": [
                                        {
                                                "internalType": "address",
                                                "name": "loanToken",
                                                "type": "address"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "amountIn",
                                                "type": "uint256"
                                        },
                                        {
                                                "internalType": "uint8",
                                                "name": "loanProvider",
                                                "type": "uint8"
                                        },
                                        {
                                                "internalType": "uint16",
                                                "name": "cycleSlippageBps",
                                                "type": "uint16"
                                        },
                                        {
                                                "components": [
                                                        {
                                                                "internalType": "uint8",
                                                                "name": "op",
                                                                "type": "uint8"
                                                        },
                                                        {
                                                                "internalType": "bytes",
                                                                "name": "data",
                                                                "type": "bytes"
                                                        }
                                                ],
                                                "internalType": "struct MultiVenueArbImplementation.Step[]",
                                                "name": "steps",
                                                "type": "tuple[]"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "minProfit",
                                                "type": "uint256"
                                        }
                                ],
                                "internalType": "struct MultiVenueArbImplementation.PlanLegacy",
                                "name": "plan",
                                "type": "tuple"
                        }
                ],
                "name": "start",
                "outputs": [
                        {
                                "internalType": "uint256",
                                "name": "grossProfit",
                                "type": "uint256"
                        }
                ],
                "stateMutability": "nonpayable",
                "type": "function"
        },
        {
                "inputs": [],
                "name": "getConfig",
                "outputs": [
                        {
                                "internalType": "uint16",
                                "name": "feeBps",
                                "type": "uint16"
                        },
                        {
                                "internalType": "uint16",
                                "name": "maxSlippageBps",
                                "type": "uint16"
                        },
                        {
                                "internalType": "uint32",
                                "name": "deadlineBuffer",
                                "type": "uint32"
                        }
                ],
                "stateMutability": "view",
                "type": "function"
        },
        {
                "inputs": [],
                "name": "owner",
                "outputs": [
                        {
                                "internalType": "address",
                                "name": "",
                                "type": "address"
                        }
                ],
                "stateMutability": "view",
                "type": "function"
        },
        {
                "inputs": [],
                "name": "permit2",
                "outputs": [
                        {
                                "internalType": "address",
                                "name": "",
                                "type": "address"
                        }
                ],
                "stateMutability": "view",
                "type": "function"
        }
]"#,
);

pub use multi_venue_arb_executor::{
    Loan as ExecutorLoan, PlanLegacy as ExecutorPlanLegacy, PlanV2 as ExecutorPlan,
    Step as ExecutorStep,
};
